name: Continuous Integration
on:
  push:
    branches:
      - main
    paths:
      - ddl/**
  workflow_dispatch:

env:
  MAKE_DATASET_SH: make_dataset.sh

jobs:
  make_dataset:
    name: BQ Make Dataset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.gcp_project_id }}
          service_account_key: ${{ secrets.gcp_sa_key }}
          export_default_credentials: true
      - name: Get Diff DDL
        uses: technote-space/get-diff-action@v5
        with:
          PATTERNS: |
            ddl/**
          FILES: |
            ${{ env.MAKE_DATASET_SH }}
      - name: Make Dataset
        if: contains(${{ env.MATCHED_FILES }}, ${{ env.MAKE_DATASET_SH }})
        run: |
          for file in ${{ env.MATCHED_FILES }} ; do
            echo $file
            sh $file
          done
