name: Daly ETL
on:
  schedule:
    - cron: '5 9 * * *'
  workflow_dispatch:

jobs:
  etl:
    name: Daily ETL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Data Lake
        run: |
          bash script/run_schedule.sh data_lake daily

      - name: Data Warehouse
        run: |
          bash script/run_schedule.sh data_warehouse daily

      - name: Slack notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: danger
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
